### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by alexlafroscia** [EmberPittsburgh/ember-2-example#1]
- [x] Update README
- [x] Pin header to top of page
- [x] Add Github link to header
- [x] Add ability to add chat messages to the conversation
- [x] Remove extra directories
